package com.UI;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

import com.DB.TestConn;
import com.Service.GetDBTressModel;
import com.Service.MakeData;
import com.Service.Tree2XML;
import com.Service.UpdXML;

/**
 *
 * @author zzd
 */
public class DataFactoryPage extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 7532578278007871440L;
	/**
     * Creates new form DataFactoryPage
     */
    public DataFactoryPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDataType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDriverType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPaneURL = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonTestLink = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneTree = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPK = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFK = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar(0,100);
        jComboBoxSelValue = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldFixValue = new javax.swing.JTextField();
        jTextFieldFromValue = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldEndValue = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldRandomLen = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonMakeData = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setTitle("造数工具");
        setAlwaysOnTop(true);
        setResizable(false);
      
        jPanel1.setToolTipText("配置连接信息");

        jLabel1.setText("请选择数据库类型：");

        jComboBoxDataType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "MySQL" }));
        jComboBoxDataType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jComboBoxDataTypeActionPerformed(evt);
            }
        });

        jLabel2.setText("请选择数据库连接方式：");

        jComboBoxDriverType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle Thin" }));

        jLabel3.setText("请输入数据库URL：");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneURL.setViewportView(jTextArea1);

        jLabel4.setText("请输入数据库用户名：");

        jLabel5.setText("请输入数据库密码：");

        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jLabel6.setText("URL Format:jdbc:oracle:thin:@<server>:<port>:<sid>");

        jButtonTestLink.setText("测试连接");
        jButtonTestLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonTestLinkActionPerformed(evt);
         
            }
        });

        jButtonNext.setText("下一步");
        jButtonNext.setEnabled(false);
        jButtonNext.setToolTipText("执行步骤较多，可能比较缓慢");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonNextActionPerformed(evt);
         
            }
        });

        jPasswordField1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTestLink)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButtonNext))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxDriverType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxDataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPaneURL, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(jTextFieldUserName)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDriverType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneURL, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTestLink)
                    .addComponent(jButtonNext))
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("配置连接信息", jPanel1);

        jTree1.setBorder(javax.swing.BorderFactory.createTitledBorder("表结构(绿色表示已配置)"));
        jTree1.setAutoscrolls(true);
        jScrollPaneTree.setViewportView(jTree1);
        jTree1.setModel(null);
        jTree1.addMouseListener(new MouseListener(){

     			@Override
     			public void mouseClicked(MouseEvent evt) {
     				// TODO Auto-generated method stub
     				int clickTimes = evt.getClickCount();
     				if (clickTimes == 2){
     					jTree1DoubleClickActionPerformed(evt);
     				}
     			}

     			@Override
     			public void mouseEntered(MouseEvent arg0) {
     				// TODO Auto-generated method stub
     				
     			}

     			@Override
     			public void mouseExited(MouseEvent arg0) {
     				// TODO Auto-generated method stub
     				
     			}

     			@Override
     			public void mousePressed(MouseEvent arg0) {
     				// TODO Auto-generated method stub
     				
     			}

     			@Override
     			public void mouseReleased(MouseEvent arg0) {
     				// TODO Auto-generated method stub
     				
     			}
             	
             });
  

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("请选择主键：");
        jLabel7.setToolTipText("");

        jTextFieldPK.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jTextFieldPK.setText("如没有主外键关系，此处不要输入内容");
        jTextFieldPK.setToolTipText("");
        jTextFieldPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });
        jTextFieldPK.addMouseListener(new MouseListener(){

			@Override
			public void mouseClicked(MouseEvent evt) {
				// TODO Auto-generated method stub
				 jTextFieldPKActionPerformed(evt);
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
        	
        });

        jLabel8.setFont(new java.awt.Font("宋体", 3, 12)); // NOI18N
        jLabel8.setText("双击左侧数据库列表中的相应字段，选择主键，可多选");

        jLabel9.setText("请选择外键：");

        jTextFieldFK.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jTextFieldFK.setText("如没有主外键关系，此处不要输入内容");
        jTextFieldFK.setToolTipText("");
        jTextFieldFK.addMouseListener(new MouseListener(){

			@Override
			public void mouseClicked(MouseEvent evt) {
				// TODO Auto-generated method stub
				jTextFieldFKActionPerformed(evt);
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
        	
        });
        
        jLabel10.setFont(new java.awt.Font("宋体", 3, 12)); // NOI18N
        jLabel10.setText("手动输入外键，格式：（表名1.主键1：表名2.外键1，表名3.外键2，表名4.外键3...；");

        jLabel11.setText("请配置字段值（选中左侧数据库列表中的字段，并为字段设置值，可多选并为其设置相同的值）");

        jLabel12.setFont(new java.awt.Font("宋体", 3, 12)); // NOI18N
        jLabel12.setText("表名5.主键2：表名6.外键4，表名7.外键5，表名8.外键6...）");

        jComboBoxSelValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "固定值", "日期范围", "数值范围", "随机字符", "随机字符包含中文" }));

        jComboBoxSelValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jComboBoxSelValueActionPerformed(evt);
            }
        });
        
        jTextFieldFixValue.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jTextFieldFixValue.setText("请输入固定值");
        jTextFieldFixValue.addMouseListener(new MouseListener(){

			@Override
			public void mouseClicked(MouseEvent evt) {
				// TODO Auto-generated method stub
				 jTextFieldFixValueActionPerformed(evt);
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
        	
        });
        jTextFieldFromValue.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jTextFieldFromValue.setText("起始值");
        jTextFieldFromValue.setEnabled(false);
        jTextFieldFromValue.addMouseListener(new MouseListener(){

			@Override
			public void mouseClicked(MouseEvent evt) {
				// TODO Auto-generated method stub
				jTextFieldFromValueActionPerformed(evt);
				
			}


			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
        	
        });

        jLabel14.setText("到");

        jTextFieldEndValue.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jTextFieldEndValue.setText("结束值");
        jTextFieldEndValue.setEnabled(false);
        jTextFieldEndValue.addMouseListener(new MouseListener(){

			@Override
			public void mouseClicked(MouseEvent evt) {
				// TODO Auto-generated method stub
				jTextFieldEndValueActionPerformed(evt);
			}

			

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
        	
        });

        jLabel15.setFont(new java.awt.Font("宋体", 3, 12)); // NOI18N
        jLabel15.setText("日期格式：yyyy-mm-dd HH:MM:SS");
        jLabel15.setToolTipText("");

        jTextFieldRandomLen.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jTextFieldRandomLen.setText("在这里输入需要的字符长度，随机字符示例：");
		jTextFieldRandomLen.setEnabled(false);
        jTextFieldRandomLen.addMouseListener(new MouseListener(){

			@Override
			public void mouseClicked(MouseEvent evt) {
				// TODO Auto-generated method stub
				jTextFieldRandomLenActionPerformed(evt);
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
        	
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jTextFieldFromValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel14)
                            .addGap(27, 27, 27)
                            .addComponent(jTextFieldEndValue, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextFieldFixValue))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextFieldRandomLen)
                                .addGap(4, 4, 4)))))
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldFixValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFromValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldEndValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldRandomLen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonSave.setText("保存");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonSaveActionPerformed(evt);
            }
        });

        jButtonMakeData.setText("开始造数");
        jButtonMakeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeDataActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("宋体", 3, 12)); // NOI18N
        jLabel13.setText("配置好一个字段记得点击保存");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldFK, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldPK, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jButtonSave)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jButtonMakeData)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPK, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldFK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jComboBoxSelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonMakeData)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("造数配置界面", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTree, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jScrollPaneTree))
                .addContainerGap())
        );

        jTabbedPane1.addTab("配置造数规则", null, jPanel2, "");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jMenu1.setText("文件");

        jMenuItem1.setText("打开配置文件");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("保存配置文件");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("另存配置文件为");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("编辑");

        jMenuItem4.setText("剪切");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("粘贴");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("复制");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("帮助");

        jMenuItem7.setText("关于");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("配置造数规则");

        pack();
    }// </editor-fold>                        

    private void jTextFieldPKActionPerformed(MouseEvent evt) {                                            
        // TODO add your handling code here:
    	if(jTextFieldPK.getText().trim().equals("如没有主外键关系，此处不要输入内容")){
    		jTextFieldPK.setText(null);
    	}
    }                                           
    private void jTextFieldFKActionPerformed(MouseEvent evt) {                                            
        // TODO add your handling code here:
    	if(jTextFieldFK.getText().trim().equals("如没有主外键关系，此处不要输入内容")){
    		jTextFieldFK.setText(null);
    	}
    }  
    private void jComboBoxSelValueActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		if(jComboBoxSelValue.getSelectedIndex() == 0){
			jTextFieldFromValue.setEnabled(false);
			jTextFieldEndValue.setEnabled(false);
			jTextFieldRandomLen.setEnabled(false);
			jTextFieldFixValue.setEnabled(true);
		}
		else if(jComboBoxSelValue.getSelectedIndex() == 1 || jComboBoxSelValue.getSelectedIndex() == 2){
			jTextFieldFromValue.setEnabled(true);
			jTextFieldEndValue.setEnabled(true);
			jTextFieldRandomLen.setEnabled(false);
			jTextFieldFixValue.setEnabled(false);
		}
		else if(jComboBoxSelValue.getSelectedIndex() == 3 || jComboBoxSelValue.getSelectedIndex() == 4){
			jTextFieldFromValue.setEnabled(false);
			jTextFieldEndValue.setEnabled(false);
			jTextFieldRandomLen.setEnabled(true);
			jTextFieldFixValue.setEnabled(false);
		}
		
		
	}
    private void jTextFieldFixValueActionPerformed(MouseEvent evt) {                                            
        // TODO add your handling code here:
    	if(jTextFieldFixValue.getText().trim().equals("请输入固定值")){
    		jTextFieldFixValue.setText(null);
    	}
    }  
    private void jTextFieldFromValueActionPerformed(MouseEvent evt) {
		// TODO Auto-generated method stub
    	if(jTextFieldFromValue.getText().trim().equals("起始值")){
    		jTextFieldFromValue.setText(null);
    	}
	}
    private void jTextFieldEndValueActionPerformed(MouseEvent evt) {
		// TODO Auto-generated method stub
    	if(jTextFieldEndValue.getText().trim().equals("结束值")){
    		jTextFieldEndValue.setText(null);
    	}
	}
    private void jTextFieldRandomLenActionPerformed(MouseEvent evt) {
		// TODO Auto-generated method stub
    	if(jTextFieldRandomLen.getText().trim().contains("在这里输入需要的字符长度，随机字符示例：")){
    		jTextFieldRandomLen.setText(null);
    	}
	}
	private void jButtonSaveActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		int comboboxValue = jComboBoxSelValue.getSelectedIndex();
//		获取选择的字段值,如果不选择则无动作
		if(jTree1.getSelectionCount() < 1){
//			do nothing	
		}else{
			String path = jTree1.getSelectionPath().toString();
			String[] col1 = path.split(",");
//			只有选择叶子节点才允许设置，否则无动作
			if(col1.length == 4 ){
				String[] col2 = col1[2].split(" ");
				String column = col1[1] + "." + col2[1];
//				定义一个数据类型
				String DataType = null;
//				定义 字段值 数组
				String [] Value = new String[2];
				
				if(comboboxValue == 0){
					DataType = "fix";
					Value[0] = jTextFieldFixValue.getText().trim(); 
				}else if(comboboxValue == 1 || comboboxValue == 2){
					DataType = "range";
					Value[0] = jTextFieldFromValue.getText().trim();
					Value[1] = jTextFieldEndValue.getText().trim();
				}else if(comboboxValue == 3 ){
					DataType = "random";
					Value[0] = jTextFieldRandomLen.getText().trim();
				}else if(comboboxValue == 4 ){
					DataType = "randomChinese";
					Value[0] = jTextFieldRandomLen.getText().trim();
				}
//				System.out.println(column + "--" + DataType + "--" + Value[0] + Value[1]);
				
				String PK = jTextFieldPK.getText().trim();
				String FK = jTextFieldFK.getText().trim();
//				开始保存字段配置
				new UpdXML(column,DataType,Value,PK,FK);
//				将已配置的字段显示为绿色
				
//				DefaultTreeCellRenderer cell = new DefaultTreeCellRenderer();
//				cell.getTreeCellRendererComponent(jTree1, (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent(), true, true, true, jTree1.getSelectionCount(), true);
//				cell.setTextSelectionColor(Color.GREEN);
//				DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
			}
		}
	}
    private void jButtonMakeDataActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	int i = JOptionPane.showConfirmDialog(null, "确定要开始造数吗？", "确认造数", JOptionPane.YES_NO_OPTION);
    	if (i == JOptionPane.YES_OPTION){
//    		开始造数
    		new MakeData();
    	}
    	else{
    	}
    }  
    private static void DataFactoryPageActionPerformed(WindowEvent e) {                                            
        // TODO add your handling code here:
    	int i = JOptionPane.showConfirmDialog(null, "确定要退出系统吗？", "退出系统", JOptionPane.YES_NO_OPTION);
    	if (i == JOptionPane.YES_OPTION){
    		System.exit(0);
    	}
    	else{
    	}
    	
    } 
	private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
//    	切换到造数界面
		jTabbedPane1.setSelectedComponent(jPanel2);
//		以树的形式展示数据库表及字段
    	TreeModel model =  GetDBTressModel.ReturnDBTreeModel();
    	jTree1.setModel(model);
//    	生成xml文件，用来保存字段配置
    	new Tree2XML().writeXML();
    }  
    private void jButtonTestLinkActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	JFrame testFrame = new JFrame("连接测试结果");
		testFrame.setVisible(true);
		testFrame.setSize(300, 100);
		testFrame.setResizable(false);
		testFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		testFrame.setLocation((ScreenInfo.getScreenWidth()-testFrame.getWidth())/2, (ScreenInfo.getScreenHeight()-testFrame.getHeight())/2);
		testFrame.setAlwaysOnTop(true);
		
		JLabel testResultLabel = new JLabel("正在测试连接中...");
		testResultLabel.setVisible(true);
		JPanel testResultJpaenl = new JPanel();
		testResultJpaenl.add(testResultLabel);
		testFrame.add(testResultJpaenl);
		JDialog testDialog = new JDialog(testFrame, "连接测试结果");
		
    	
		TestConn conn = new TestConn();
		String url = jTextArea1.getText().trim();
		String username = jTextFieldUserName.getText().trim();
		String pwd = jPasswordField1.getText().trim();
		if(url.length() == 0 || username.length() == 0 || pwd.length() == 0){
			testResultLabel.setText("请输入连接信息");
		}
		else{
			int constate = conn.returnResult(url, username, pwd);
			if (constate == 0){
				testResultLabel.setText("连接失败，请检查输入的URL等信息！");
			}
			else if(constate == 2){
				testResultLabel.setText("连接失败，连接出现异常！");
			}
			else if(constate == 1){
				testResultLabel.setText("连接成功！");
				jButtonNext.setEnabled(true);
			}
		}
		
    }   

	private void jTree1DoubleClickActionPerformed(MouseEvent evt) {
		// TODO Auto-generated method stub
		String selPath  = jTree1.getSelectionPath().toString();
		String[] pkValue2handle = selPath.split(",");
//		如果双击的不是 叶子节点（也就是 字段）则不做任何处理
		if(pkValue2handle.length == 3){
//			获取表名和字段，格式：  表名.字段名
			String pkValue = pkValue2handle[1].trim() + "." + pkValue2handle[2].replace("]", "").trim();
			if (jTextFieldPK.getText().trim().length() == 0 || jTextFieldPK.getText().trim().equals("如没有主外键关系，此处不要输入内容")){
				jTextFieldPK.setText(pkValue + ";");
			}
			else if (jTextFieldPK.getText().trim().contains(pkValue)){
//				do nothing
			}
			else{
				jTextFieldPK.setText(jTextFieldPK.getText().trim() + pkValue + ";");
			}
			
		}
	
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataFactoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataFactoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataFactoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataFactoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               JFrame  DataFactoryPage = new DataFactoryPage();
               DataFactoryPage.setVisible(true);
               DataFactoryPage.setAlwaysOnTop(false);
               DataFactoryPage.setLocation((ScreenInfo.getScreenWidth()-DataFactoryPage.getWidth())/2, (ScreenInfo.getScreenHeight()-DataFactoryPage.getHeight())/2);
               DataFactoryPage.addWindowListener(new WindowAdapter(){
            		@Override
            		public void windowClosing(WindowEvent e) {
            			DataFactoryPageActionPerformed(e);
            		}
               });
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonTestLink;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonMakeData;
    private javax.swing.JComboBox<String> jComboBoxDataType;
    private javax.swing.JComboBox<String> jComboBoxDriverType;
    private javax.swing.JComboBox<String> jComboBoxSelValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPaneURL;
    private javax.swing.JScrollPane jScrollPaneTree;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextFieldUserName;
    private javax.swing.JTextField jTextFieldPK;
    private javax.swing.JTextField jTextFieldFK;
    private javax.swing.JTextField jTextFieldFixValue;
    private javax.swing.JTextField jTextFieldFromValue;
    private javax.swing.JTextField jTextFieldEndValue;
    private javax.swing.JTextField jTextFieldRandomLen;
    private javax.swing.JTree jTree1;
    
    // End of variables declaration                   

}

